export const SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS settings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  gender TEXT NOT NULL DEFAULT '男',
  parent_phone TEXT NOT NULL DEFAULT '',
  role TEXT NOT NULL DEFAULT '',
  group_no INTEGER NOT NULL DEFAULT 1,
  level TEXT NOT NULL DEFAULT '良',
  afternoon_care INTEGER NOT NULL DEFAULT 1,
  remark TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS classroom_config (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_count INTEGER NOT NULL DEFAULT 6,
  col_count INTEGER NOT NULL DEFAULT 8,
  desk_label TEXT NOT NULL DEFAULT '双人课桌'
);

CREATE TABLE IF NOT EXISTS leave_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_name TEXT NOT NULL,
  leave_type TEXT NOT NULL DEFAULT '事假',
  reason TEXT NOT NULL DEFAULT '',
  start_date TEXT NOT NULL DEFAULT '',
  end_date TEXT NOT NULL DEFAULT '',
  hours REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS discipline_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  student_name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT '常规纪律',
  content TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS grades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  exam_name TEXT NOT NULL DEFAULT '',
  subject TEXT NOT NULL DEFAULT '语文',
  student_name TEXT NOT NULL,
  score REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS homework (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  subject TEXT NOT NULL DEFAULT '语文',
  assign_date TEXT NOT NULL DEFAULT '',
  requirement TEXT NOT NULL DEFAULT '',
  deadline TEXT NOT NULL DEFAULT '',
  submitted INTEGER NOT NULL DEFAULT 0,
  late INTEGER NOT NULL DEFAULT 0,
  missing INTEGER NOT NULL DEFAULT 0,
  missing_names TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS schedules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT '备课',
  duration_min INTEGER NOT NULL DEFAULT 60,
  done INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS timetable (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  weekday INTEGER NOT NULL DEFAULT 1,
  period TEXT NOT NULL DEFAULT '正课',
  subject TEXT NOT NULL DEFAULT '',
  is_chinese INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS todos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  date TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '待办',
  priority TEXT NOT NULL DEFAULT '普通'
);

CREATE TABLE IF NOT EXISTS conversations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  student_name TEXT NOT NULL,
  topic TEXT NOT NULL DEFAULT '',
  content TEXT NOT NULL DEFAULT '',
  effect TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS home_visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  student_name TEXT NOT NULL,
  way TEXT NOT NULL DEFAULT '电话',
  content TEXT NOT NULL DEFAULT '',
  is_meeting INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS evaluation (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_name TEXT NOT NULL,
  moral INTEGER NOT NULL DEFAULT 3,
  study INTEGER NOT NULL DEFAULT 3,
  sports INTEGER NOT NULL DEFAULT 3,
  art INTEGER NOT NULL DEFAULT 3,
  labor INTEGER NOT NULL DEFAULT 3,
  comment TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS parent_comm (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  student_name TEXT NOT NULL,
  way TEXT NOT NULL DEFAULT '微信',
  content TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS safety_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '课间',
  content TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS peiyou_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  student_name TEXT NOT NULL,
  subject TEXT NOT NULL DEFAULT '语文',
  weak_point TEXT NOT NULL DEFAULT '',
  target_score REAL NOT NULL DEFAULT 0,
  record TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS work_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date TEXT NOT NULL DEFAULT '',
  title TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT '班级管理',
  place TEXT NOT NULL DEFAULT '',
  hours REAL NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS seats (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  row_index INTEGER NOT NULL,
  col_index INTEGER NOT NULL,
  student_name TEXT NOT NULL DEFAULT ''
);
`;
